### ISSUE TITLE
propagate CNAMEx into axis names

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/xarray-fits#27]
This should be simple enough, right? Will help streamline the pipeline.

Also, while we're at it, could you use CRVAL/CDELT/CRPIX to set up the axes?

**Comment by sjperkins** [comment]
> This should be simple enough, right? Will help streamline the pipeline.

I understand this to mean using CNAME's as DataArray dimension names?

> Also, while we're at it, could you use CRVAL/CDELT/CRPIX to set up the axes?

IIRC we discussed this at the busy week.

I think, in the general case, that the FITS coordinates wlll need to be as big as the data since the FITS header can represent multiple coordinate systems (linear, spherical).

https://www.aanda.org/articles/aa/full_html/2010/16/aa15362-10/aa15362-10.html#S196

Even the linear coordinate system supports scaling and shearing so I don' think it would be as simple as setting up xarray coordinates for each axis. 

The WCS `pix_to_world` method outputs coordinates as large as the data.

**Comment by sjperkins** [comment]
CNAME's apply to the Spectral Coordinate FITS extension. I don't think they applly to all FITS systems.

https://www.aanda.org/articles/aa/pdf/2006/05/aa3818-05.pdf

An intermediate measure might just be to use the following:

- https://docs.xarray.dev/en/latest/generated/xarray.Dataset.rename_dims.html
- https://docs.xarray.dev/en/latest/generated/xarray.DataArray.rename.html

if you know your FITS cube contains Spectral Coordinates

**Comment by o-smirnov** [comment]
> I understand this to mean using CNAME's as DataArray dimension names?

Yes, exactly. CNAMEs can be treated as arbitrary labels for this purpose. Just read them off and treat them as dimension names.

> CNAME's apply to the Spectral Coordinate FITS extension. I don't think they applly to all FITS systems.

No, CNAMEs apply to all axes. In the first instance they're just axis labels. It's just that some CNAMEs are special when you start getting into interesting coordinate systems.

> Even the linear coordinate system supports scaling and shearing so I don' think it would be as simple as setting up xarray coordinates for each axis.

You're overthinking it. :) There's always an underlying "raw" axis coordinate given by CDEL, CRPIX and CRVAL, and this is what we should propagate into the xarray coordinates. 

For the more complicated coordinates, it will be up to the user to construct an astropy WCS object from the header. Simple enough.

**Comment by sjperkins** [comment]
> You're overthinking it. :) There's always an underlying "raw" axis coordinate given by CDEL, CRPIX and CRVAL, and this is what we should propagate into the xarray coordinates.

Ah! Ok I see what you're getting at. Yeah, if we're not getting involved with the WCS system then I'm far less concerned.

**Comment by o-smirnov** [comment]
Yeah the WCS is as simple as:

```wcs = WCS(fits.Header(dataset.attrs['header']))```

so we absolutely do not need to worry about it.
