### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by miguelcarcamov** [ratt-ru/xarray-fits#3]
Hello,

Just a silly question (or maybe not)... Is this still an ongoing project? because the last commit was on 2018... has the repo been moved to another one? or it's better to use another library?

Cheers

**Comment by sjperkins** [comment]
Hi @miguelcarcamov. At some point I would like to update it and add FITS file writing support, which is currently lacking.

**Comment by miguelcarcamov** [comment]
Hi @sjperkins I have install the library with pip3 but it seems to be an error when using it. I am also think on how to do the fits.write without doing the compute previously.

**Comment by miguelcarcamov** [comment]
Cool, I will give it a try and I will let you know

**Comment by sjperkins** [comment]
With the recent releases, `xarray-fits` has been modernised and is ready for use.
